config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  resources :users
  resources :companies
  resources :students
  resources :questions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  COMPANY_SIZES = ['1-10', '11-20', '21-30', '31-50', '51-100', '101-500', '501-1000'].freeze
  paginates_per 10
  has_many :users

  validates :name, :about, :city, :country, :size, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  paginates_per 10
  validates :title, :answer, presence: true
  validates :title, uniqueness: true
end

app/models/student.rb
class Student < ApplicationRecord
  paginates_per 10
  has_one_attached :passport_photo

  validates :name, :email, :current_status, :contact_number, :alternate_contact_number, :college, :address, :date_of_birth, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  paginates_per 10
  belongs_to :company
  validates :name, :role, :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  def index
    @companies = Company.all.page(params[:page])
  end


  def new
    @company = Company.new
  end



  def create
    @company = Company.new(company_params)
    if @company.save
      redirect_to companies_path
    else
      render :new
    end
  end



  def show
    @company = Company.find(params[:id])
  end

  def edit
    @company = Company.find(params[:id])
  end



  def update
    @company = Company.find(params[:id])
    if @company.update(company_params)
      redirect_to companies_path
    else
      render :edit
    end
  end



  def destroy
    @company = Company.find(params[:id])
    @company.destroy
    redirect_to companies_path
  end

  private

  def company_params
    params.require(:company).permit(:name, :about, :city, :country, :size)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[show edit update destroy]
  
  def index
    @questions = Question.all.page(params[:page])
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    respond_to do |format|
    if @question.save
      format.js
      format.html { redirect_to questions_path, notice: 'Question created'}
    else
      format.js
      format.html { render :new, status: :unprocessable_entity }
    end
  end
end

  def show
    
  end

  def edit
    
  end

  def update
    respond_to do |format|
    if @question.update(question_params)
      format.js
      format.html { redirect_to @question, notice: 'Question updated'}
    else
      format.js
      format.html{ render :edit, status: :unprocessable_entity }
    end
  end
end

  def destroy
     @question.destroy
     respond_to do |format|
      format.js
      format.html { redirect_to questions_path, notice: "Question was successfully destroyed"}
  end
end

  private

  def question_params
    params.require(:question).permit(:title, :answer)
  end

  def set_question
    @question = Question.find(params[:id])
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @q = Student.ransack(params[:q])
    @students = @q.result(distinct: true).page(params[:page])
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to students_path
    else
      render :new
    end
  end

  def show
    @student = Student.find(params[:id])
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    if @student.update(student_params)
      redirect_to students_path
    else
      render :edit
    end
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to students_path
  end

  private

  def student_params
    params.require(:student).permit(:name, :email, :current_status, :contact_number, :alternate_contact_number, :address, :date_of_birth, :passport_photo, :college)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]


  def index
    @q = User.ransack(params[:q])
    @users = @q.result(distinct:true).order(created_at: :desc).page(params[:page])
  end


  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.js
        format.html { redirect_to users_path, notice: 'User created at'}
      else
        format.js
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end


  def show

  end


  def edit
    
  end


  def update
    respond_to do |format|
      if @user.update(user_params)
        format.js
        format.html { redirect_to @user, notice: 'User updated'}
      else
        format.js
        format.html{ render :edit, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @user.destroy
    respond_to do |format|
    format.html { redirect_to users_path, notice: "User was successfully destroyed"}
    format.js
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :role, :email, :company_id)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/companies/_form.html.erb
<%= form_with model: @company do |form| %>


  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control form-control-lg" %>
    <% @company.errors.full_messages_for(:name).each do |message| %>
    <p class="text-danger"><%= message %></p>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :about %>
    <%= form.text_field :about, class: "form-control form-control-lg" %>
    <% @company.errors.full_messages_for(:about).each do |message| %>
    <p class="text-danger"><%= message %></p>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :city %>
    <%= form.text_field :city, class: "form-control form-control-lg" %>
    <% @company.errors.full_messages_for(:city).each do |message| %>
    <p class="text-danger"><%= message %></p>
    <% end %>
  </div>


  <div class="form-group">
    <%= form.label :country %>
    <%= form.text_field :country, class: "form-control form-control-lg" %>
    <% @company.errors.full_messages_for(:country).each do |message| %>
    <p class="text-danger"><%= message %></p>
    <% end %>
  </div>


  <div class="form-group">
    <%= form.label :size %>
    <%= form.select :size, options_for_select(Company::COMPANY_SIZES, selected: @company.size), {prompt: 'Select Company type'}, {class: 'form-control form-control-lg rounded-0'} %>
    <% @company.errors.full_messages_for(:company_size).each do |message| %>
    <p class="text-danger"><%= message %></p>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.submit class: "btn btn-primary btn-lg" %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<div class="col-lg-8">
  <h1>Edit Company</h1>

  <%= render "form" %>
</div>

app/views/companies/index.html.erb
<div class="col-lg-10 mt-3">
  <h1>All Listed Companies are Below:</h1>

  <%= link_to 'New Company', new_company_path, class: "btn btn-primary btn-lg" %>

  <table class="table table-bordered mt-5">
    <thead>
      <tr>
        <th>Name</th>
        <th>About</th>
        <th>City</th>
        <th>Country</th>
        <th>Size</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.about %></td>
        <td><%= company.city %></td>
        <td><%= company.country %></td>
        <td><%= company.size %></td>
        <td>
         <div class="dropdown">
           <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
             Actions
           </button>
           <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <%= link_to 'View' , company, class: "dropdown-item" %>
            <%= link_to 'Edit' , edit_company_path(company), class: "dropdown-item" %>
            <%= link_to 'Delete', company, method: :delete, data: {confirm: 'Are you sure?'}, class: "dropdown-item" %>
           </div>
         </div>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @companies %>
</div>

app/views/companies/new.html.erb
<div class="col-lg-8">
  <h1>New Company</h1>

  <%= render "form" %>
</div>

app/views/companies/show.html.erb
<h1>Company Details</h1>

<p><strong>Name: </strong><%= @company.name %></p>
<p><strong>About: </strong><%= @company.about %></p>
<p><strong>City: </strong><%= @company.city %></p>
<p><strong>Country: </strong><%= @company.country %></p>
<p><strong>Size: </strong><%= @company.size %></p>

<%= link_to 'Back', companies_path %> | <%= link_to 'Edit' , edit_company_path(@company) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectTaskAssignment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/header" %>
    <div class ="container">
     <div class="row">
        <%= yield %>       
     </div> 
    </div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/questions/_error.html.erb
 <% if question.errors.any? %>
  <div id= "error_explanation">
    <h6 class="text-danger"><%= pluralize(question.errors.count, "error") %> Prohibited this user from being saved:</h6>
    <% question.errors.each do |error| %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <strong><%= error.full_message %></strong>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>    
  <% end %>
  </div>
 <% end %>

app/views/questions/_form.html.erb
<%= form_with(model: @question, local: false) do |form| %>

  <div class="modal-body">
    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: "form-control form-control-lg" %>
    </div>  


    <div class= "form-group">
      <%= form.label :answer %>
      <%= form.text_field :answer, class: "form-control form-control-lg"  %>
    </div>
  </div>


  <div class="modal-footer">
    <button type="button" class="btn btn-secondary btn-lg close-modal" data-dismiss="modal">Close</button>
    <%= form.submit class: "btn btn-primary btn-lg" %>
  </div>

  
<% end %>

app/views/questions/_question_row.html.erb
<div class="card mt-3 mb-2" id="questionRow_<%= question.id %>">
  <div class="card-header" id="headingOne">
    <h5 class="mb-0">
      <button class="btn btn-link" data-toggle="collapse" data-target="#collapse_<%= question.id %>" aria-expanded="true" aria-controls="collapse_<%= question.id %>">
        <h4><%= question.title %></h4>
      </button>
    </h5>
  </div>

  <div id="collapse_<%= question.id %>" class="collapse" aria-labelledby="heading_<%= question.id %>" data-parent="#accordion">
    <div class="card-body">
      <p class="lead"><%= truncate(question.answer, length: 100) %></p>
      <% if question.answer.length > 100 %>
        <%= link_to 'View Full Answer' , question, class: "btn btn-info", data: { toggle: 'modal', target: '#showQuestionModal', remote: true } %>
      <% end %>
      <%= link_to 'Edit' , edit_question_path(question), class: "btn btn-success", data: { toggle: 'modal', target: '#editQuestionModal', remote: true } %>
      <%= link_to 'Delete', question, class: "btn btn-danger", method: :delete, data: {confirm: 'Are you sure?', remote: true } %>
    </div>
  </div>
</div>

app/views/questions/_show.html.erb
<div class="modal-body">
  <div class="col-lg-12">
    <p class="lead"><%= question.answer %></p>
  </div>
</div>

<div class="modal-footer">
  <button type="button" class="btn btn-secondary btn-lg close-modal" data-dismiss="modal">Close</button>
</div>

app/views/questions/create.js.erb
<% if @question.errors.any? %>
 $("#errorArea").html("<%= escape_javascript render('error', question: @question)%>")
 <% else %>
 $("#questionsTable").prepend("<%= escape_javascript render('question_row', question: @question)%>");
 $(".close-modal").click();
<% end %>

app/views/questions/destroy.js.erb
$("#questionRow_<%= @question.id %>").remove();

app/views/questions/edit.html.erb
<div class="col-lg-8">
  <h1>Edit Question</h1>

  <%= render "form" %>
</div>

app/views/questions/edit.js.erb
$("#editQuestionform").html("<%= escape_javascript render('form', question: @question)%>");

app/views/questions/index.html.erb
<div class="col-lg-12 mt-3">
  <h1>Questions and Answer</h1>

  <%= link_to 'New Question', new_question_path, class: "btn btn-primary btn-lg", data: { toggle: 'modal', target: '#newQuestionModal', remote: true } %>


  
    <div id="accordion">
      <% @questions.each do |question| %>
        <%= render "questions/question_row", question: question %>
      <% end %>
    </div>
  

<%= paginate @questions %>


<div class="modal fade" id="newQuestionModal" tabindex="-1" role="dialog"aria-labelledby="newQuestionModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newQuestionModalLabel">Create New Question</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div id="newQuestionform">
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="editQuestionModal" tabindex="-1" role="dialog"aria-labelledby="editQuestionModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editQuestionModalLabel">Edit Question</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
        <div id="editQuestionform">
        </div>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="showQuestionModal" tabindex="-1" role="dialog"aria-labelledby="showQuestionModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="showQuestionModalLabel">Show Full Answer  </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div id="showQuestionDetails">
      </div>
    </div>
  </div>
</div>

</div>

app/views/questions/new.html.erb
<div class="col-lg-8">
  <h1>New Question</h1>

  <%= render "form" %>
</div>

app/views/questions/new.js.erb
$("#newQuestionform").html("<%= escape_javascript render('form', question: @question)%>");

app/views/questions/show.html.erb
<div class="col-lg-10">
  <div class="card rounded-0 shadow mt-5">
    <div class="card-body">
      <h1>Question and Answer</h1>


      <p><strong>Title: </strong><%= @question.title %></p>
      <p><strong>Answer: </strong><%= @question.answer %></p>
      <%= link_to 'Back', questions_path, class: "btn btn-primary" %> 
      <%= link_to 'Edit' , edit_question_path(@question), class: "btn btn-secondary" %>
    </div>
  </div>
</div>

app/views/questions/show.js.erb
$("#showQuestionDetails").html("<%= escape_javascript render('show', question: @question)%>");

app/views/questions/update.js.erb
<% if @question.errors.any? %>
 $("#errorArea").html("<%= escape_javascript render('error', question: @question)%>")
 <% else %>
 $("#questionRow_<%= @question.id %>").replaceWith("<%= escape_javascript render('question_row', question: @question)%>");
 $(".close-modal").click();
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer bg-primary p-1">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h1 class="text-center">Appsimpact Technologies</h1>
      </div>
    </div>
  </div>
</footer>


<!-- <style>
  .footer {
    background-color: #EEDD82;
    position: relative;
    bottom: 0;
    /*bottom: 0;
    width: 100%;
    height: 60px;
    line-height: 60px;*/
  }
</style> -->

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="/">Student Details</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
    </ul>
  </div>
</nav>

app/views/students/_form.html.erb
<%= form_with model: @student do |form| %>


  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control form-control-lg" %>
    <% @student.errors.full_messages_for(:name).each do |message| %>
    <p class="text-danger"><%= message %></p>
    <% end %>
  </div>


  <div class= "form-group">
    <%= form.label :email %>
    <%= form.email_field :email, class: "form-control form-control-lg"  %>
    <% @student.errors.full_messages_for(:email).each do |message| %>
    <p class="text-danger"><%= message %></p>
    <% end %>
  </div>


  <div class="form-group">
    <%= form.label :current_status %>
    <%= form.text_field :current_status, class: "form-control form-control-lg"  %>
    <% @student.errors.full_messages_for(:current_status).each do |message| %>
    <p class="text-danger"><%= message %></p>
    <% end %>
  </div>


  
  <div class="form-group">
    <%= form.label :contact_number %>
    <%= form.text_field :contact_number, class: "form-control form-control-lg" %>
    <% @student.errors.full_messages_for(:contact_number).each do |message| %>
    <p class="text-danger"><%= message %></p>
    <% end %>
  </div>
  
  <div class="form-group">
    <%= form.label :alternate_contact_number %>
    <%= form.text_field :alternate_contact_number, class: "form-control form-control-lg"%>
    <% @student.errors.full_messages_for(:alternate_contact_number).each do |message| %>
    <p class="text-danger"><%= message %></p>
    <% end %>
  </div>


  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address, class: "form-control form-control-lg" %>
    <% @student.errors.full_messages_for(:address).each do |message| %>
    <p class="text-danger"><%= message %></p>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :date_of_birth %>
    <%= form.date_field :date_of_birth, class: "form-control form-control-lg" %>
    <% @student.errors.full_messages_for(:date_of_birth).each do |message| %>
    <p class="text-danger"><%= message %></p>
    <% end %>
  </div>
      
  <label for="validationTooltip01">Passport Photo</label>
  <div class="custom-file">
    <%= form.label :passport_photo, for: "student_passport_photo", class: "custom-file-label" %>
    <%= form.file_field :passport_photo, class: "custom-file-input form-control form-control-lg"  %>
    <% @student.errors.full_messages_for(:passport_photo).each do |message| %>
    <p class="text-danger"><%= message %></p>
    <% end %>
  </div>

<!-- 
  <div class="custom-file">
    <input type="file" class="custom-file-input" id="customFile">
    <label class="custom-file-label" for="customFile">Choose file</label>
  </div> -->

  <div class="form-group">
    <%= form.label :college %>
    <%= form.text_field :college, class: "form-control form-control-lg"%>
    <% @student.errors.full_messages_for(:college).each do |message| %>
    <p class="text-danger"><%= message %></p>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.submit class: "btn btn-primary btn-lg" %>
  </div>
<% end %>

app/views/students/edit.html.erb
<div class="col-lg-8">
  <h1>Edit Student</h1>

  <%= render "form" %>
</div>

app/views/students/index.html.erb
<div class="col-lg-10 mt-3">
  <%= search_form_for @q, url: :students do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name_cont, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit class: "btn btn-primary btn-lg" %>
  </div>
  
  <% end %>
 <h1> All Student</h1>

 <%= link_to 'New Student', new_student_path, class: "btn btn-primary btn-lg" %>

 <table class ="table table-bordered mt-5">
   <thead>
     <tr>
       <th>Name</th>
       <th>Email</th>
       <th>Current_Status</th>
       <th>Actions</th>
     </tr>
   </thead>
   <tbody>
     <% @students.each do |student| %>
       <tr>
         <td><%= student.name %></td>
         <td><%= student.email %></td>
         <td><%= student.current_status %></td>
          <td>
           <div class="dropdown">
             <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               Actions
             </button>
             <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <%= link_to 'View' , student, class: "dropdown-item" %>
              <%= link_to 'Edit' , edit_student_path(student), class: "dropdown-item" %>
              <%= link_to 'Delete', student, method: :delete, data: {confirm: 'Are you sure?'}, class: "dropdown-item" %>
             </div>
           </div>
          </td>
       </tr>
     <% end %>
   </tbody>
 </table>
 <%= paginate @students %>
</div>

app/views/students/new.html.erb
<div class="col-lg-8">
  <h1>New Student</h1>

  <%= render "form" %>
</div>

app/views/students/show.html.erb
<div class="col-lg-10">
  <div class="card rounded-0 shadow mt-5">
    <div class="card-body">
      <h1>Student Details</h1>


      <p><strong>Name: </strong><%= @student.name %></p>
      <p><strong>Email: </strong><%= @student.email %></p>
      <p><strong>Current_Status: </strong><%= @student.current_status %></p>
      <p><strong>Contact_Number: </strong><%= @student.contact_number %></p>
      <p><strong>Alternate_Contact_Number: </strong><%= @student.alternate_contact_number %></p>
      <p><strong>Address: </strong><%= @student.address %></p>
      <p><strong>Date_of_Birth: </strong><%= @student.date_of_birth %></p>
      <p><strong>Passport_Photo: </strong><%= image_tag @student.passport_photo, style: "width: 100px; height: 100px"  %></p>
      <p><strong>College: </strong><%= @student.college %></p>

      <%= link_to 'Back', students_path, class: "btn btn-primary" %> 
      <%= link_to 'Edit' , edit_student_path(@student), class: "btn btn-secondary" %>
    </div>
  </div>
</div>

<!-- 

# header footer
# to make proper bootstrap on every model -->

app/views/users/_user_row.html.erb
<tr id="userRow_<%= user.id %>">
    <td><%= user.name %></td>
  <td><%= user.role %></td>
  <td><%= user.email %></td>
  <td>
  <div class="dropdown">
    <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Actions
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
     <%= link_to 'View' , user, class: "dropdown-item", data: {
      toggle: 'modal', target: '#showUserModal', remote: true
     } %>
     <%= link_to 'Edit' , edit_user_path(user), class: "dropdown-item", data: {toggle: 'modal', target: '#editUserModal', remote: true } %>
     <%= link_to 'Delete', user, method: :delete, data: {confirm: 'Are you sure?', remote: true}, class: "dropdown-item"%>
    </div>
  </div>
  </td>
</tr>

app/views/users/destroy.js.erb
$("#userRow_<%= @user.id %>").remove();

app/views/users/edit.html.erb
<div class="col-lg-8">
  <h1>Edit User</h1>

  <%= render "form" %>
</div>

app/views/users/index.html.erb
<div class="col-lg-10 mt-3">

<%= search_form_for @q do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name_cont, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.email_field :email_cont, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :role %>
    <%= form.text_field :role_cont, class:"form-control" %>
  </div>

  <div class="form-group">
  <%= form.label :company_name %>
  <%= form.search_field :company_name_cont, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit class: "btn btn-primary" %>
    <%= link_to 'Reset', users_path, class: "btn btn-success" %>
  </div>

<% end %>


<h1>All Users</h1>

<%= link_to 'New User', new_user_path, class: "btn btn-primary btn-lg", data: { toggle: 'modal', target: '#newUserModal', remote: true } %>

  <table class ="table table-bordered mt-5">
    <thead>
      <tr>
        <th>Name</th>
        <th>Role</th>
        <th>Email</th>
        <th>Actions</th>
      </tr>
    </thead>  
    <tbody id="usersTable">
      <% @users.each do |user| %>
      <%= render 'user_row', user: user %>
      <% end %>
    </tbody>
  </table>

<%= paginate @users %>
  <div class="modal fade" id="newUserModal" tabindex="-1" role="dialog"aria-labelledby="newUserModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="newUserModalLabel">Create New User</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>

        <div id="newUserform">
        </div>
      </div>
    </div>
  </div>


  <div class="modal fade" id="editUserModal" tabindex="-1" role="dialog"aria-labelledby="editUserModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="editUserModalLabel">Edit User</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>

        <div id="editUserform">
        </div>
      </div>
    </div>
  </div>


  <div class="modal fade" id="showUserModal" tabindex="-1" role="dialog"aria-labelledby="showUserModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="showUserModalLabel">User Details</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>

        <div id="showUserDetails">
        </div>
      </div>
    </div>
  </div>


</div>

app/views/users/show.html.erb
<h1>User Details</h1>

<p><strong>Name: </strong><%= @user.name %></p>
<p><strong>Role: </strong><%= @user.role %></p>
<p><strong>Email: </strong><%= @user.email %></p>


<%= link_to 'Back', users_path %> | <%= link_to 'Edit' , edit_user_path(@user) %>